# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\mac_101_inbalance_table.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form, processingObject):
        self.processingObject = processingObject
        self.asdu = processingObject.asdu
        self.device = self.asdu.interfaces[processingObject.processingInterfaceIndex].protocols[processingObject.processingProtocolIndex].devices[processingObject.processingDeviceIndex]
        
        Form.setObjectName("Form")
        
        font = QtGui.QFont()
        font.setPointSize(8)
        Form.setFont(font)
        Form.setStyleSheet("QWidget {\n"
"    background-color: white;\n"
"}")
        Form.resizeEvent = lambda event: self.resizeEvent(event)
        Form.closeEvent = lambda event: self.closeEvent(event, self.asdu)
        self.form = Form
        self.frame_8 = QtWidgets.QFrame(Form)
        self.frame_8.setGeometry(QtCore.QRect(0, 0, 1440, 40))
        self.frame_8.setStyleSheet("QFrame { background-color: #c4c4c4; }")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.pushButton = QtWidgets.QPushButton(self.frame_8)
        self.pushButton.setGeometry(QtCore.QRect(40, 10, 140, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton { border: none; border-top-left-radius: 5px; border-top-right-radius: 5px; background-color: transparent; }")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 10, 140, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton { border: none; border-top-left-radius: 5px; border-top-right-radius: 5px; }")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(0, 100, self.form.rect().width(), self.form.rect().height() - 100))
        self.scrollArea.setMinimumSize(QtCore.QSize(1366, 728))
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setStyleSheet("QScrollArea { border: none; }")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.save = QtWidgets.QPushButton(Form)
        self.save.setGeometry(QtCore.QRect(1000, 50, 155, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.save.setFont(font)
        self.save.setStyleSheet("QPushButton { border-radius: 5px; background-color: #FED2AA; }")
        self.save.setObjectName("save")
        self.save.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel = QtWidgets.QPushButton(Form)
        self.cancel.setGeometry(QtCore.QRect(800, 50, 155, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cancel.setFont(font)
        self.cancel.setStyleSheet("QPushButton { border-radius: 5px; background-color: #C4C4C4; }")
        self.cancel.setObjectName("cancel")
        self.cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settingsRender()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def settingsRender(self):
        _translate = QtCore.QCoreApplication.translate
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, self.form.rect().width(), self.form.rect().height() - 100))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setMinimumSize(QtCore.QSize(1366, 984))
        self.groupBox.setStyleSheet("QGroupBox { border: none; }")
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.frame_9 = QtWidgets.QFrame(self.groupBox)
        self.frame_9.setGeometry(QtCore.QRect(40, 27, 380, 145))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_8 = QtWidgets.QLabel(self.frame_9)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 380, 60))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.frame_16 = QtWidgets.QFrame(self.frame_9)
        self.frame_16.setGeometry(QtCore.QRect(0, 75, 221, 70))
        self.frame_16.setStyleSheet("QFrame { border: none; }")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.label_15 = QtWidgets.QLabel(self.frame_16)
        self.label_15.setGeometry(QtCore.QRect(0, 0, 221, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.comboBox = QtWidgets.QComboBox(self.frame_16)
        self.comboBox.setGeometry(QtCore.QRect(0, 40, 221, 30))
        self.comboBox.setStyleSheet("QComboBox { border: none; background-color: rgb(130, 130, 130, 30); }")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setGeometry(QtCore.QRect(40, 200, 1360, 700))
        self.frame.setStyleSheet("QFrame { background-color: rgba(130, 130, 130, 30); border: 2px solid #aaa; }")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 1360, 440))
        self.tableWidget.setStyleSheet("QTableWidget { border: none; }\n"
"QTableWidget QHeaderView { border: none; }\n"
"QTableWidget, QTableWidget QHeaderView:section, QTableWidget QHeaderView {\n"
"     background-color: transparent; \n"
"}\n"
"QHeaderView::section { border: 1px solid #aaa; }")
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideLeft)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setRowCount(int(self.device.data["rowsCount"]))

        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(int(self.device.data["columnCount"]))

        
        for i in range(int(self.device.data["rowsCount"])):
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setVerticalHeaderItem(i, item)
        
        for i in range(int(self.device.data["columnCount"])):
            item = QtWidgets.QTableWidgetItem()
            font = QtGui.QFont()
            font.setPointSize(11)
            item.setFont(font)
            item.setText(_translate("Form", self.device.columnNames["column_%d" % (i + 1)]))
            self.tableWidget.setHorizontalHeaderItem(i, item)

        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(False)

        for i in range(int(self.device.data["columnCount"])):
            for j in range(int(self.device.data["rowsCount"])):
                item = QtWidgets.QTableWidgetItem()
                font = QtGui.QFont()
                font.setPointSize(11)
                item.setFont(font)
                item.setBackground(QtGui.QColor(0, 0, 0, 0))
                if "column_%d" % (i + 1) in self.device.data:
                    item.setText(self.device.data["column_%d" % (i + 1)].get("row_%d" % (j + 1)))
                
                self.tableWidget.setItem(j, i, item)
        self.tableWidget.itemChanged.connect(self.updateDeviceTableSetting)

        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 440, 1360, 260))
        self.frame_2.setStyleSheet("QFrame { background-color: white; border: 2px solid #aaa; }")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(55, 22, 155, 219))
        self.frame_3.setStyleSheet("QFrame { border: none; }")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(0, 0, 155, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel { border: none; }")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 46, 155, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton { border-radius: 5px; background-color: #FED2AA; }")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 138, 155, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton { border-radius: 5px; background-color: #FED2AA; }")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 92, 155, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton { border-radius: 5px; background-color: #FED2AA; }")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_6.setGeometry(QtCore.QRect(0, 184, 155, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton { border-radius: 5px; background-color: #FED2AA; }")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(241, 22, 70, 219))
        self.frame_4.setStyleSheet("QFrame { border: none; }")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 70, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel { border: none; }")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit.setGeometry(QtCore.QRect(0, 46, 70, 35))
        self.lineEdit.setStyleSheet("QLineEdit { border: 1px solid #aaa; }")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_2.setGeometry(QtCore.QRect(0, 92, 70, 35))
        self.lineEdit_2.setStyleSheet("QLineEdit { border: 1px solid #aaa; }")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_3.setGeometry(QtCore.QRect(0, 138, 70, 35))
        self.lineEdit_3.setStyleSheet("QLineEdit { border: 1px solid #aaa; }")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_4.setGeometry(QtCore.QRect(0, 184, 70, 35))
        self.lineEdit_4.setStyleSheet("QLineEdit { border: 1px solid #aaa; }")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setGeometry(QtCore.QRect(342, 22, 90, 219))
        self.frame_6.setStyleSheet("QFrame { border: none; }")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 90, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel { border: none; }")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_9.setGeometry(QtCore.QRect(0, 46, 90, 35))
        self.lineEdit_9.setStyleSheet("QLineEdit { border: 1px solid #aaa; }")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_10.setGeometry(QtCore.QRect(0, 92, 90, 35))
        self.lineEdit_10.setStyleSheet("QLineEdit { border: 1px solid #aaa; }")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_11.setGeometry(QtCore.QRect(0, 138, 90, 35))
        self.lineEdit_11.setStyleSheet("QLineEdit { border: 1px solid #aaa; }")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_12.setGeometry(QtCore.QRect(0, 184, 90, 35))
        self.lineEdit_12.setStyleSheet("QLineEdit { border: 1px solid #aaa; }")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.checkBox = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox.setGeometry(QtCore.QRect(512, 80, 110, 30))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_2.setGeometry(QtCore.QRect(512, 140, 110, 30))
        self.checkBox_2.setObjectName("checkBox_2")
        self.frame_10 = QtWidgets.QFrame(self.frame_2)
        self.frame_10.setGeometry(QtCore.QRect(702, 22, 70, 219))
        self.frame_10.setStyleSheet("QFrame { border: none; }")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_6 = QtWidgets.QLabel(self.frame_10)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 70, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel { border: none; }")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_17.setGeometry(QtCore.QRect(0, 46, 70, 35))
        self.lineEdit_17.setStyleSheet("QLineEdit { border: 1px solid #aaa; }")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_19.setGeometry(QtCore.QRect(0, 138, 70, 35))
        self.lineEdit_19.setStyleSheet("QLineEdit { border: 1px solid #aaa; }")
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_20.setGeometry(QtCore.QRect(0, 184, 70, 35))
        self.lineEdit_20.setStyleSheet("QLineEdit { border: 1px solid #aaa; }")
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.frame_12 = QtWidgets.QFrame(self.frame_2)
        self.frame_12.setGeometry(QtCore.QRect(832, 22, 115, 219))
        self.frame_12.setStyleSheet("QFrame { border: none; }")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_9 = QtWidgets.QLabel(self.frame_12)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 115, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel { border: none; }")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.frame_12)
        self.lineEdit_24.setGeometry(QtCore.QRect(0, 46, 115, 35))
        self.lineEdit_24.setStyleSheet("QLineEdit { border: 1px solid #aaa; }")
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.frame_12)
        self.lineEdit_25.setGeometry(QtCore.QRect(0, 92, 115, 35))
        self.lineEdit_25.setStyleSheet("QLineEdit { border: 1px solid #aaa; }")
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.frame_12)
        self.lineEdit_26.setGeometry(QtCore.QRect(0, 138, 115, 35))
        self.lineEdit_26.setStyleSheet("QLineEdit { border: 1px solid #aaa; }")
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.frame_12)
        self.lineEdit_27.setGeometry(QtCore.QRect(0, 184, 115, 35))
        self.lineEdit_27.setStyleSheet("QLineEdit { border: 1px solid #aaa; }")
        self.lineEdit_27.setObjectName("lineEdit_27")

        self.label_8.setText(_translate("Form", "МЭК 101 Небалансный (%s)" % (self.device.name)))
        self.label_15.setText(_translate("Form", "Типовый набор параметров:"))
        self.comboBox.setItemText(0, _translate("Form", "-"))
        self.save.setText(_translate("Form", "Сохранить"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("Form", "Группа параметров"))
        self.pushButton_4.setText(_translate("Form", "Все"))
        self.pushButton_7.setText(_translate("Form", "ТИ"))
        self.pushButton_5.setText(_translate("Form", "DI и DO"))
        self.pushButton_6.setText(_translate("Form", "ТИИ"))
        self.label_2.setText(_translate("Form", "Адрес"))
        self.label_4.setText(_translate("Form", "Период, с"))
        self.checkBox.setText(_translate("Form", "Отн. апертура"))
        self.checkBox_2.setText(_translate("Form", "Отн. апертура"))
        self.label_6.setText(_translate("Form", "Апертура"))
        self.label_9.setText(_translate("Form", "Команды опроса"))
        self.cancel.setText(_translate("Form", "Отмена"))

        self.verticalLayout.addWidget(self.groupBox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

    def closeEvent(self, event, obj):
        obj.cancel()

    def resizeEvent(self, event):
        self.scrollArea.setGeometry(QtCore.QRect(0, 100, self.form.rect().width(), self.form.rect().height() - 100))
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, self.form.rect().width(), self.form.rect().height() - 100))

    def updateDeviceTableSetting(self, item):
        i = item.row()
        j = item.column()
        if not "column_%d" % (j + 1) in self.device.data:
            self.device.data["column_%d" % j] = dict()
        
        self.device.data["column_%d" % (j + 1)]["row_%d" % (i + 1)] = item.text()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", self.device.name))
        self.pushButton.setText(_translate("Form", "Настройки"))
        self.pushButton_2.setText(_translate("Form", "Таблица"))
