# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\tcp_clients.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1440, 1024)
        font = QtGui.QFont()
        font.setPointSize(8)
        Form.setFont(font)
        Form.setStyleSheet("QWidget {\n"
"    background-color: white;\n"
"}")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(56, 44, 271, 246))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 168, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(194, 0, 77, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(0, 27, 168, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QComboBox {\n"
"    background-color: rgba(196, 196, 196, 30);\n"
"    border: none;\n"
"}\n"
"")
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.spinBox = QtWidgets.QSpinBox(self.frame)
        self.spinBox.setGeometry(QtCore.QRect(194, 27, 77, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spinBox.setFont(font)
        self.spinBox.setStyleSheet("QSpinBox, QSpinBox:hover, QSpinBox:active {\n"
"    background-color: rgba(196, 196, 196, 30);\n"
"    border: none;\n"
"}\n"
"\n"
"QSpinBox:up-button, QSpinBox:down-button {\n"
"    border: none;\n"
"}\n"
"\n"
"")
        self.spinBox.setObjectName("spinBox")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 70, 271, 30))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.spinBox_2 = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox_2.setGeometry(QtCore.QRect(221, 0, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setStyleSheet("QSpinBox, QSpinBox:hover, QSpinBox:active {\n"
"    background-color: rgba(196, 196, 196, 30);\n"
"    border: none;\n"
"}\n"
"\n"
"QSpinBox:up-button, QSpinBox:down-button {\n"
"    border: none;\n"
"}\n"
"\n"
"")
        self.spinBox_2.setObjectName("spinBox_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(0, 105, 271, 30))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.spinBox_3 = QtWidgets.QSpinBox(self.frame_3)
        self.spinBox_3.setGeometry(QtCore.QRect(221, 0, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spinBox_3.setFont(font)
        self.spinBox_3.setStyleSheet("QSpinBox, QSpinBox:hover, QSpinBox:active {\n"
"    background-color: rgba(196, 196, 196, 30);\n"
"    border: none;\n"
"}\n"
"\n"
"QSpinBox:up-button, QSpinBox:down-button {\n"
"    border: none;\n"
"}\n"
"\n"
"")
        self.spinBox_3.setObjectName("spinBox_3")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(0, 140, 271, 30))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.spinBox_4 = QtWidgets.QSpinBox(self.frame_4)
        self.spinBox_4.setGeometry(QtCore.QRect(221, 0, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spinBox_4.setFont(font)
        self.spinBox_4.setStyleSheet("QSpinBox, QSpinBox:hover, QSpinBox:active {\n"
"    background-color: rgba(196, 196, 196, 30);\n"
"    border: none;\n"
"}\n"
"\n"
"QSpinBox:up-button, QSpinBox:down-button {\n"
"    border: none;\n"
"}\n"
"\n"
"")
        self.spinBox_4.setObjectName("spinBox_4")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(0, 175, 271, 30))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.spinBox_5 = QtWidgets.QSpinBox(self.frame_5)
        self.spinBox_5.setGeometry(QtCore.QRect(221, 0, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spinBox_5.setFont(font)
        self.spinBox_5.setStyleSheet("QSpinBox, QSpinBox:hover, QSpinBox:active {\n"
"    background-color: rgba(196, 196, 196, 30);\n"
"    border: none;\n"
"}\n"
"\n"
"QSpinBox:up-button, QSpinBox:down-button {\n"
"    border: none;\n"
"}\n"
"\n"
"")
        self.spinBox_5.setObjectName("spinBox_5")
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setGeometry(QtCore.QRect(0, 210, 271, 30))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.spinBox_6 = QtWidgets.QSpinBox(self.frame_6)
        self.spinBox_6.setGeometry(QtCore.QRect(221, 0, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spinBox_6.setFont(font)
        self.spinBox_6.setStyleSheet("QSpinBox, QSpinBox:hover, QSpinBox:active {\n"
"    background-color: rgba(196, 196, 196, 30);\n"
"    border: none;\n"
"}\n"
"\n"
"QSpinBox:up-button, QSpinBox:down-button {\n"
"    border: none;\n"
"}\n"
"\n"
"")
        self.spinBox_6.setObjectName("spinBox_6")
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.frame_7 = QtWidgets.QFrame(Form)
        self.frame_7.setGeometry(QtCore.QRect(405, 44, 729, 246))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_8 = QtWidgets.QLabel(self.frame_7)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 168, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.pushButton = QtWidgets.QPushButton(self.frame_7)
        self.pushButton.setGeometry(QtCore.QRect(0, 34, 153, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    text-align: left;\n"
"    border-color: rgba(196, 196, 196, 30);\n"
"    background-color: rgba(196, 196, 196, 30);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_2.setGeometry(QtCore.QRect(153, 34, 153, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    text-align: left;\n"
"    border-color: rgba(196, 196, 196, 30);\n"
"    background-color: rgba(196, 196, 196, 15);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_3.setGeometry(QtCore.QRect(459, 34, 153, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    text-align: left;\n"
"    border-color: rgba(196, 196, 196, 30);\n"
"    background-color: rgba(196, 196, 196, 15);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_4.setGeometry(QtCore.QRect(306, 34, 153, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    text-align: left;\n"
"    border-color: rgba(196, 196, 196, 30);\n"
"    background-color: rgba(196, 196, 196, 15);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setGeometry(QtCore.QRect(0, 81, 729, 165))
        self.frame_8.setStyleSheet("QFrame {\n"
"    background-color: rgba(196, 196, 196, 30);\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setGeometry(QtCore.QRect(60, 28, 216, 27))
        self.frame_9.setStyleSheet("QFrame {\n"
"    background-color: transparent;\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_9 = QtWidgets.QLabel(self.frame_9)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 111, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_5.setGeometry(QtCore.QRect(111, 0, 105, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: #FED2AA;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.frame_10 = QtWidgets.QFrame(self.frame_8)
        self.frame_10.setGeometry(QtCore.QRect(60, 85, 216, 27))
        self.frame_10.setStyleSheet("QFrame {\n"
"    background-color: transparent;\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_10 = QtWidgets.QLabel(self.frame_10)
        self.label_10.setGeometry(QtCore.QRect(0, 0, 111, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_6.setGeometry(QtCore.QRect(111, 0, 105, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: #FED2AA;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.frame_11 = QtWidgets.QFrame(self.frame_8)
        self.frame_11.setGeometry(QtCore.QRect(335, 28, 216, 27))
        self.frame_11.setStyleSheet("QFrame {\n"
"    background-color: transparent;\n"
"}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_11 = QtWidgets.QLabel(self.frame_11)
        self.label_11.setGeometry(QtCore.QRect(0, 0, 111, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_7.setGeometry(QtCore.QRect(111, 0, 105, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background-color: #FED2AA;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(56, 309, 1328, 2))
        self.line.setStyleSheet("Line {\n"
"    border: none; background-color: #999999; \n"
"}")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.frame_12 = QtWidgets.QFrame(Form)
        self.frame_12.setGeometry(QtCore.QRect(56, 350, 271, 557))
        self.frame_12.setStyleSheet("QFrame { background-color: transparent; }")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_8.setGeometry(QtCore.QRect(0, 0, 271, 49))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    background-color: #c4c4c4;\n"
"    border-radius: 7px;\n"
"    border: 0px;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_9.setGeometry(QtCore.QRect(0, 147, 271, 49))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 0px;\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_10.setGeometry(QtCore.QRect(0, 98, 271, 49))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 0px;\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_11.setGeometry(QtCore.QRect(0, 49, 271, 49))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 0px;\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_12.setGeometry(QtCore.QRect(0, 196, 271, 49))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 0px;\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(405, 350, 729, 557))
        self.scrollArea.setMinimumSize(QtCore.QSize(729, 557))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 718, 848))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setMinimumSize(QtCore.QSize(700, 830))
        self.groupBox.setStyleSheet("QGroupBox { border: none; }")
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox.setFlat(True)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_13.setGeometry(QtCore.QRect(510, 764, 155, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_13.setStyleSheet("QPushButton {\n"
"    background-color: #FED2AA;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.line_4 = QtWidgets.QFrame(self.groupBox)
        self.line_4.setGeometry(QtCore.QRect(349, 380, 2, 309))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_3 = QtWidgets.QFrame(self.groupBox)
        self.line_3.setGeometry(QtCore.QRect(35, 378, 630, 2))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.frame_27 = QtWidgets.QFrame(self.groupBox)
        self.frame_27.setGeometry(QtCore.QRect(35, 399, 295, 290))
        self.frame_27.setStyleSheet("QFrame { border: none; }")
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.label_28 = QtWidgets.QLabel(self.frame_27)
        self.label_28.setGeometry(QtCore.QRect(2, 40, 176, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("QLabel { border: none; }")
        self.label_28.setObjectName("label_28")
        self.frame_28 = QtWidgets.QFrame(self.frame_27)
        self.frame_28.setGeometry(QtCore.QRect(2, 150, 177, 70))
        self.frame_28.setStyleSheet("QFrame { border: none; }")
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.label_29 = QtWidgets.QLabel(self.frame_28)
        self.label_29.setGeometry(QtCore.QRect(0, 0, 177, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_28)
        self.lineEdit_10.setGeometry(QtCore.QRect(0, 40, 177, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setStyleSheet("QLineEdit { border: 1px solid #aaaaaa; }")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.frame_32 = QtWidgets.QFrame(self.frame_27)
        self.frame_32.setGeometry(QtCore.QRect(2, -2, 176, 40))
        self.frame_32.setStyleSheet("QFrame { border: none; }")
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.checkBox_7 = QtWidgets.QCheckBox(self.frame_32)
        self.checkBox_7.setGeometry(QtCore.QRect(0, 0, 176, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setStyleSheet("QCheckBox { border: none; background-color: transparent; }")
        self.checkBox_7.setObjectName("checkBox_7")
        self.frame_29 = QtWidgets.QFrame(self.frame_27)
        self.frame_29.setGeometry(QtCore.QRect(2, 220, 176, 70))
        self.frame_29.setStyleSheet("QFrame { border: none; }")
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.label_30 = QtWidgets.QLabel(self.frame_29)
        self.label_30.setGeometry(QtCore.QRect(0, 0, 176, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.comboBox_5 = QtWidgets.QComboBox(self.frame_29)
        self.comboBox_5.setGeometry(QtCore.QRect(0, 40, 176, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setStyleSheet("QComboBox {\n"
"    background-color: rgba(196, 196, 196, 30);\n"
"    border: none;\n"
"}\n"
"")
        self.comboBox_5.setEditable(False)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.frame_33 = QtWidgets.QFrame(self.frame_27)
        self.frame_33.setGeometry(QtCore.QRect(2, 80, 177, 70))
        self.frame_33.setStyleSheet("QFrame { border: none; }")
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.label_31 = QtWidgets.QLabel(self.frame_33)
        self.label_31.setGeometry(QtCore.QRect(0, 0, 177, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_33)
        self.lineEdit_11.setGeometry(QtCore.QRect(0, 40, 177, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setStyleSheet("QLineEdit { border: 1px solid #aaaaaa; }")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.pushButton_17 = QtWidgets.QPushButton(self.frame_27)
        self.pushButton_17.setGeometry(QtCore.QRect(190, 260, 105, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_17.setStyleSheet("QPushButton {\n"
"    background-color: #FED2AA;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}")
        self.pushButton_17.setObjectName("pushButton_17")
        self.frame_34 = QtWidgets.QFrame(self.frame_27)
        self.frame_34.setGeometry(QtCore.QRect(190, 80, 105, 70))
        self.frame_34.setStyleSheet("QFrame { border: none; }")
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.label_32 = QtWidgets.QLabel(self.frame_34)
        self.label_32.setGeometry(QtCore.QRect(0, 0, 105, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_34)
        self.lineEdit_12.setGeometry(QtCore.QRect(0, 40, 105, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setStyleSheet("QLineEdit { border: 1px solid #aaaaaa; }")
        self.lineEdit_12.setText("")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.frame_35 = QtWidgets.QFrame(self.groupBox)
        self.frame_35.setGeometry(QtCore.QRect(370, 399, 295, 290))
        self.frame_35.setStyleSheet("QFrame { border: none; }")
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.label_33 = QtWidgets.QLabel(self.frame_35)
        self.label_33.setGeometry(QtCore.QRect(2, 40, 176, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("QLabel { border: none; }")
        self.label_33.setObjectName("label_33")
        self.frame_36 = QtWidgets.QFrame(self.frame_35)
        self.frame_36.setGeometry(QtCore.QRect(2, 150, 177, 70))
        self.frame_36.setStyleSheet("QFrame { border: none; }")
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.label_34 = QtWidgets.QLabel(self.frame_36)
        self.label_34.setGeometry(QtCore.QRect(0, 0, 177, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.frame_36)
        self.lineEdit_13.setGeometry(QtCore.QRect(0, 40, 177, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setStyleSheet("QLineEdit { border: 1px solid #aaaaaa; }")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.frame_37 = QtWidgets.QFrame(self.frame_35)
        self.frame_37.setGeometry(QtCore.QRect(2, -2, 176, 40))
        self.frame_37.setStyleSheet("QFrame { border: none; }")
        self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.checkBox_8 = QtWidgets.QCheckBox(self.frame_37)
        self.checkBox_8.setGeometry(QtCore.QRect(0, 0, 176, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_8.setFont(font)
        self.checkBox_8.setStyleSheet("QCheckBox { border: none; background-color: transparent; }")
        self.checkBox_8.setObjectName("checkBox_8")
        self.frame_38 = QtWidgets.QFrame(self.frame_35)
        self.frame_38.setGeometry(QtCore.QRect(2, 220, 176, 70))
        self.frame_38.setStyleSheet("QFrame { border: none; }")
        self.frame_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.label_35 = QtWidgets.QLabel(self.frame_38)
        self.label_35.setGeometry(QtCore.QRect(0, 0, 176, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.comboBox_6 = QtWidgets.QComboBox(self.frame_38)
        self.comboBox_6.setGeometry(QtCore.QRect(0, 40, 176, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_6.setFont(font)
        self.comboBox_6.setStyleSheet("QComboBox {\n"
"    background-color: rgba(196, 196, 196, 30);\n"
"    border: none;\n"
"}\n"
"")
        self.comboBox_6.setEditable(False)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.frame_39 = QtWidgets.QFrame(self.frame_35)
        self.frame_39.setGeometry(QtCore.QRect(2, 80, 177, 70))
        self.frame_39.setStyleSheet("QFrame { border: none; }")
        self.frame_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.label_36 = QtWidgets.QLabel(self.frame_39)
        self.label_36.setGeometry(QtCore.QRect(0, 0, 177, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.frame_39)
        self.lineEdit_14.setGeometry(QtCore.QRect(0, 40, 177, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setStyleSheet("QLineEdit { border: 1px solid #aaaaaa; }")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.pushButton_18 = QtWidgets.QPushButton(self.frame_35)
        self.pushButton_18.setGeometry(QtCore.QRect(190, 260, 105, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_18.setStyleSheet("QPushButton {\n"
"    background-color: #FED2AA;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}")
        self.pushButton_18.setObjectName("pushButton_18")
        self.frame_40 = QtWidgets.QFrame(self.frame_35)
        self.frame_40.setGeometry(QtCore.QRect(190, 80, 105, 70))
        self.frame_40.setStyleSheet("QFrame { border: none; }")
        self.frame_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.label_37 = QtWidgets.QLabel(self.frame_40)
        self.label_37.setGeometry(QtCore.QRect(0, 0, 105, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.frame_40)
        self.lineEdit_15.setGeometry(QtCore.QRect(0, 40, 105, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_15.setFont(font)
        self.lineEdit_15.setStyleSheet("QLineEdit { border: 1px solid #aaaaaa; }")
        self.lineEdit_15.setText("")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(35, 2, 155, 49))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("QLabel { border: none; }")
        self.label_12.setObjectName("label_12")
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setGeometry(QtCore.QRect(349, 69, 2, 309))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.frame_22 = QtWidgets.QFrame(self.groupBox)
        self.frame_22.setGeometry(QtCore.QRect(370, 70, 295, 290))
        self.frame_22.setStyleSheet("QFrame { border: none; }")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.label_23 = QtWidgets.QLabel(self.frame_22)
        self.label_23.setGeometry(QtCore.QRect(2, 40, 176, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("QLabel { border: none; }")
        self.label_23.setObjectName("label_23")
        self.frame_23 = QtWidgets.QFrame(self.frame_22)
        self.frame_23.setGeometry(QtCore.QRect(2, 150, 177, 70))
        self.frame_23.setStyleSheet("QFrame { border: none; }")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.label_24 = QtWidgets.QLabel(self.frame_23)
        self.label_24.setGeometry(QtCore.QRect(0, 0, 177, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_23)
        self.lineEdit_7.setGeometry(QtCore.QRect(0, 40, 177, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet("QLineEdit { border: 1px solid #aaaaaa; }")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.frame_31 = QtWidgets.QFrame(self.frame_22)
        self.frame_31.setGeometry(QtCore.QRect(2, -2, 176, 40))
        self.frame_31.setStyleSheet("QFrame { border: none; }")
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.checkBox_6 = QtWidgets.QCheckBox(self.frame_31)
        self.checkBox_6.setGeometry(QtCore.QRect(0, 0, 176, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setStyleSheet("QCheckBox { border: none; background-color: transparent; }")
        self.checkBox_6.setObjectName("checkBox_6")
        self.frame_24 = QtWidgets.QFrame(self.frame_22)
        self.frame_24.setGeometry(QtCore.QRect(2, 220, 176, 70))
        self.frame_24.setStyleSheet("QFrame { border: none; }")
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.label_25 = QtWidgets.QLabel(self.frame_24)
        self.label_25.setGeometry(QtCore.QRect(0, 0, 176, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.comboBox_4 = QtWidgets.QComboBox(self.frame_24)
        self.comboBox_4.setGeometry(QtCore.QRect(0, 40, 176, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setStyleSheet("QComboBox {\n"
"    background-color: rgba(196, 196, 196, 30);\n"
"    border: none;\n"
"}\n"
"")
        self.comboBox_4.setEditable(False)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.frame_25 = QtWidgets.QFrame(self.frame_22)
        self.frame_25.setGeometry(QtCore.QRect(2, 80, 177, 70))
        self.frame_25.setStyleSheet("QFrame { border: none; }")
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.label_26 = QtWidgets.QLabel(self.frame_25)
        self.label_26.setGeometry(QtCore.QRect(0, 0, 177, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_25)
        self.lineEdit_8.setGeometry(QtCore.QRect(0, 40, 177, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setStyleSheet("QLineEdit { border: 1px solid #aaaaaa; }")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.pushButton_16 = QtWidgets.QPushButton(self.frame_22)
        self.pushButton_16.setGeometry(QtCore.QRect(190, 260, 105, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_16.setStyleSheet("QPushButton {\n"
"    background-color: #FED2AA;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}")
        self.pushButton_16.setObjectName("pushButton_16")
        self.frame_26 = QtWidgets.QFrame(self.frame_22)
        self.frame_26.setGeometry(QtCore.QRect(190, 80, 105, 70))
        self.frame_26.setStyleSheet("QFrame { border: none; }")
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.label_27 = QtWidgets.QLabel(self.frame_26)
        self.label_27.setGeometry(QtCore.QRect(0, 0, 105, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_26)
        self.lineEdit_9.setGeometry(QtCore.QRect(0, 40, 105, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setStyleSheet("QLineEdit { border: 1px solid #aaaaaa; }")
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.frame_17 = QtWidgets.QFrame(self.groupBox)
        self.frame_17.setGeometry(QtCore.QRect(35, 69, 295, 290))
        self.frame_17.setStyleSheet("QFrame { border: none; }")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.label_18 = QtWidgets.QLabel(self.frame_17)
        self.label_18.setGeometry(QtCore.QRect(2, 40, 176, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("QLabel { border: none; }")
        self.label_18.setObjectName("label_18")
        self.frame_18 = QtWidgets.QFrame(self.frame_17)
        self.frame_18.setGeometry(QtCore.QRect(2, 150, 177, 70))
        self.frame_18.setStyleSheet("QFrame { border: none; }")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.label_19 = QtWidgets.QLabel(self.frame_18)
        self.label_19.setGeometry(QtCore.QRect(0, 0, 177, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_18)
        self.lineEdit_4.setGeometry(QtCore.QRect(0, 40, 177, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("QLineEdit { border: 1px solid #aaaaaa; }")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.frame_30 = QtWidgets.QFrame(self.frame_17)
        self.frame_30.setGeometry(QtCore.QRect(2, -2, 176, 40))
        self.frame_30.setStyleSheet("QFrame { border: none; }")
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.checkBox_5 = QtWidgets.QCheckBox(self.frame_30)
        self.checkBox_5.setGeometry(QtCore.QRect(0, 0, 176, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setStyleSheet("QCheckBox { border: none; background-color: transparent; }")
        self.checkBox_5.setObjectName("checkBox_5")
        self.frame_19 = QtWidgets.QFrame(self.frame_17)
        self.frame_19.setGeometry(QtCore.QRect(2, 220, 176, 70))
        self.frame_19.setStyleSheet("QFrame { border: none; }")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.label_20 = QtWidgets.QLabel(self.frame_19)
        self.label_20.setGeometry(QtCore.QRect(0, 0, 176, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_19)
        self.comboBox_3.setGeometry(QtCore.QRect(0, 40, 176, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setStyleSheet("QComboBox {\n"
"    background-color: rgba(196, 196, 196, 30);\n"
"    border: none;\n"
"}\n"
"")
        self.comboBox_3.setEditable(False)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.frame_20 = QtWidgets.QFrame(self.frame_17)
        self.frame_20.setGeometry(QtCore.QRect(2, 80, 177, 70))
        self.frame_20.setStyleSheet("QFrame { border: none; }")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.label_21 = QtWidgets.QLabel(self.frame_20)
        self.label_21.setGeometry(QtCore.QRect(0, 0, 177, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_20)
        self.lineEdit_5.setGeometry(QtCore.QRect(0, 40, 177, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("QLineEdit { border: 1px solid #aaaaaa; }")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_15.setGeometry(QtCore.QRect(190, 260, 105, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_15.setStyleSheet("QPushButton {\n"
"    background-color: #FED2AA;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}")
        self.pushButton_15.setObjectName("pushButton_15")
        self.frame_21 = QtWidgets.QFrame(self.frame_17)
        self.frame_21.setGeometry(QtCore.QRect(190, 80, 105, 70))
        self.frame_21.setStyleSheet("QFrame { border: none; }")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.label_22 = QtWidgets.QLabel(self.frame_21)
        self.label_22.setGeometry(QtCore.QRect(0, 0, 105, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_21)
        self.lineEdit_6.setGeometry(QtCore.QRect(0, 40, 105, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("QLineEdit { border: 1px solid #aaaaaa; }")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout.addWidget(self.groupBox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Telemechanics"))
        self.label.setText(_translate("Form", "Выберите УСПД:"))
        self.label_2.setText(_translate("Form", "Кол-во:"))
        self.comboBox.setItemText(0, _translate("Form", "АТЛАС 1"))
        self.comboBox.setItemText(1, _translate("Form", "АТЛАС 2"))
        self.label_3.setText(_translate("Form", "Кол-во Ethernet(Bridge):"))
        self.label_4.setText(_translate("Form", "Кол-во Ethernet:"))
        self.label_5.setText(_translate("Form", "Кол-во RS-485:"))
        self.label_6.setText(_translate("Form", "Кол-во RS-232:"))
        self.label_7.setText(_translate("Form", "Кол-во CAN:"))
        self.label_8.setText(_translate("Form", "Интерфейсы:"))
        self.pushButton.setText(_translate("Form", "Ethernet"))
        self.pushButton_2.setText(_translate("Form", "RS-485"))
        self.pushButton_3.setText(_translate("Form", "CAN"))
        self.pushButton_4.setText(_translate("Form", "RS-232"))
        self.label_9.setText(_translate("Form", "Ethernet-1"))
        self.pushButton_5.setText(_translate("Form", "Настроить"))
        self.label_10.setText(_translate("Form", "Ethernet-2"))
        self.pushButton_6.setText(_translate("Form", "Настроить"))
        self.label_11.setText(_translate("Form", "Ethernet-3"))
        self.pushButton_7.setText(_translate("Form", "Настроить"))
        self.pushButton_8.setText(_translate("Form", "Ethernet-1"))
        self.pushButton_9.setText(_translate("Form", "Резервирование"))
        self.pushButton_10.setText(_translate("Form", "Ethernet-3"))
        self.pushButton_11.setText(_translate("Form", "Ethernet-2"))
        self.pushButton_12.setText(_translate("Form", "TCP клиенты"))
        self.pushButton_13.setText(_translate("Form", "Сохранить"))
        self.label_28.setText(_translate("Form", "TCP клиент 3"))
        self.label_29.setText(_translate("Form", "TCP Keep Alive:"))
        self.checkBox_7.setText(_translate("Form", "Не используется"))
        self.label_30.setText(_translate("Form", "Выберите протокол:"))
        self.comboBox_5.setItemText(0, _translate("Form", "МЭК 104"))
        self.comboBox_5.setItemText(1, _translate("Form", "61850"))
        self.label_31.setText(_translate("Form", "IP-адрес:"))
        self.pushButton_17.setText(_translate("Form", "Настроить"))
        self.label_32.setText(_translate("Form", "Порт:"))
        self.label_33.setText(_translate("Form", "TCP клиент 4"))
        self.label_34.setText(_translate("Form", "TCP Keep Alive:"))
        self.checkBox_8.setText(_translate("Form", "Не используется"))
        self.label_35.setText(_translate("Form", "Выберите протокол:"))
        self.comboBox_6.setItemText(0, _translate("Form", "МЭК 104"))
        self.comboBox_6.setItemText(1, _translate("Form", "61850"))
        self.label_36.setText(_translate("Form", "IP-адрес:"))
        self.pushButton_18.setText(_translate("Form", "Настроить"))
        self.label_37.setText(_translate("Form", "Порт:"))
        self.label_12.setText(_translate("Form", "TCP клиенты"))
        self.label_23.setText(_translate("Form", "TCP клиент 2"))
        self.label_24.setText(_translate("Form", "TCP Keep Alive:"))
        self.checkBox_6.setText(_translate("Form", "Не используется"))
        self.label_25.setText(_translate("Form", "Выберите протокол:"))
        self.comboBox_4.setItemText(0, _translate("Form", "МЭК 104"))
        self.comboBox_4.setItemText(1, _translate("Form", "61850"))
        self.label_26.setText(_translate("Form", "IP-адрес:"))
        self.pushButton_16.setText(_translate("Form", "Настроить"))
        self.label_27.setText(_translate("Form", "Порт:"))
        self.label_18.setText(_translate("Form", "TCP клиент 1"))
        self.label_19.setText(_translate("Form", "TCP Keep Alive:"))
        self.checkBox_5.setText(_translate("Form", "Не используется"))
        self.label_20.setText(_translate("Form", "Выберите протокол:"))
        self.comboBox_3.setItemText(0, _translate("Form", "МЭК 104"))
        self.comboBox_3.setItemText(1, _translate("Form", "61850"))
        self.label_21.setText(_translate("Form", "IP-адрес:"))
        self.pushButton_15.setText(_translate("Form", "Настроить"))
        self.label_22.setText(_translate("Form", "Порт:"))
